name: Modify Other Repo

on:
  push:
    branches:
      - main  # 可以根据需要触发此 Action

jobs:
  modify-file:
    runs-on: ubuntu-latest
    steps:
      # 检出另一个存储库
      - name: Checkout other repository
        uses: actions/checkout@v3
        with:
          repository: ss556699ss/springboot-mail 
          token:  "${{ secrets.NOTEBOOK }}"
          path: other-repo

      - name: use mikefarah/yq@v4.44.3
        uses: mikefarah/yq@v4.44.3
        
      - name: Modify YAML file
        run: |
          cd  other-repo
          ls
          cd  other-repo && ls && yq -i '.key = "new value2"' test.yaml 

      # 提交更改
      - name: Commit and push changes
        run: |
          cd other-repo
          git config --global user.name "ss556699ss"
          git config --global user.email "s22027761@gmail.com"
          git add .
          git commit -m "Update YAML file"
          git push
        env:
          GITHUB_TOKEN: "${{ secrets.NOTEBOOK }}"
