name: Modify Other Repo

on:
  push:
    branches:
      - main  # 可以根据需要触发此 Action

jobs:
  modify-file:
    runs-on: ubuntu-latest
    steps:
      # 检出当前存储库（可选）
      - name: Checkout this repository
        uses: actions/checkout@v3

      # 检出另一个存储库
      - name: Checkout other repository
        uses: actions/checkout@v3
        with:
          repository: ss556699ss/Notebook 
          token:  "${{ secrets.NOTEBOOK }}"
          path: other-repo

      # 修改目标 YAML 文件
      - name: Modify YAML file
        run: |
          ls
          # 这里你可以用 sed、yq 或其他工具来修改 YAML 文件
          yq eval '.key = "new value"' -i test.yaml  # 修改 YAML 文件的值

      # # 提交更改
      # - name: Commit and push changes
      #   run: |
      #     cd other-repo
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git add path/to/yourfile.yaml
      #     git commit -m "Update YAML file"
      #     git push
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # 使用 Token 推送更改
